### ISSUE TITLE
BUG: Updating existing database not possible

### ISSUE THREAD

**Issue by jerdra** [jerdra/niviz-rater#12]
**Is your feature request related to a problem? Please describe.**
Currently when the index tries to build without the `--use-existing-index` flag it assumes that no DB file exists in the current directory. With `--use-existing-index` the index build will skip indexing entirely. This means that if a researcher wants to update their existing database it is not possible to do so 

**Describe the solution you'd like**
The `--use-existing-index` flag should be complimented by a `--no-updates` flag. This means that by default the index builder will attempt to find new files to update the database with. Using `--no-updates` should skip this step entirely.

A caveat to this process is that we expect that the user does not change their YAML config file from what is represented in the database. Appropriate handling will be required here (i.e represent the YAML file in the DB and check against it?).

**Comment by sguthrie** [comment]
I'd enjoy working on this :)

**Comment by jerdra** [comment]
Closed with #19
