### ISSUE TITLE
ENH: YAML schema validation

### ISSUE THREAD

**Issue by jerdra** [jerdra/niviz-rater#6]
niviz-rater enforces a YAML schema for configuring the qc process. The following are captured:

1. Description for how to initialize rows

2. QC components
- Column name (generated from BIDS entities)
- Applicable ratings for a given component
- A set of BIDS descriptors to use when pulling in images for a given component

 The following schema generation and validation framework seems like a promising option:

https://github.com/23andMe/Yamale

**Comment by nathankchan** [comment]
Claiming this!

**Comment by jerdra** [comment]
The previous PR added a validator but the implementation needs a small update to be complete, so re-opening! The implementation will be complete with #18!
